# -*- coding: utf-8 -*-
"""Telco_Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0Nj7ftco70Bo1k_ywKt9LEnQHLZBqga
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import sklearn
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
from matplotlib import colormaps
sns.set_palette('Set3')
sns.set_style("darkgrid")
from warnings import filterwarnings
filterwarnings(action="ignore")
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder,OrdinalEncoder
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, confusion_matrix, precision_score, recall_score, accuracy_score, f1_score, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import FunctionTransformer
import pickle
import joblib
import os

print(f"numpy == {np.__version__}")
print(f"pandas == {pd.__version__}")
print(f"seaborn == {sns.__version__}")
print(matplotlib.__version__)
print(f"joblib == {joblib.__version__}")
print(f"scikit-learn {sklearn.__version__}")
file_path = "WA_Fn-UseC_-Telco-Customer-Churn.csv"
# Load the data into a pandas DataFrame
try:
    df = pd.read_csv(file_path)
    print(f"Data loaded successfully from {file_path}.")
except FileNotFoundError:
    print(f"Error: The file at {file_path} was not found. Please check the path and try again.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

"""**`Exploratory analysis`**"""

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors="coerce")

df.pivot_table(columns="Contract", aggfunc={"TotalCharges":"sum"})

# df.groupby(["Contract", "Churn"]).size().unstack().plot(
#     kind="bar",
#     stacked=True,
#     figsize=(5, 5)
# )
#
# plt.xlabel("Contract")
# plt.ylabel("Count")
# plt.xticks(rotation=0)
# plt.show()
#
# df.groupby(["SeniorCitizen", "Churn"]).size().unstack().plot(
#     kind="bar",
#     stacked=True,
#     figsize=(5, 5)
#     );
#
# plt.xlabel("Age Group")
# plt.ylabel("Count")
# plt.xticks([0, 1],["Young", "Old"])
# plt.show()
#
# newer_customers = df[df["tenure"] <= 6]
# older_customers = df[df["tenure"] > 6]
#
# newer_customers["Churn"].value_counts(normalize=True)
#
# older_customers["Churn"].value_counts(normalize=True)

def data_preprocessor(df):

    df = df.copy()

    # Convert TotalCharges to numeric
    df["TotalCharges"] = pd.to_numeric(
        df["TotalCharges"],
        errors="coerce"
    )

    df["TotalCharges"] = df["TotalCharges"].fillna(0)

    # Drop unnecessary columns
    X = df.drop(
        columns=[
            "customerID",
            "PaymentMethod",
            "PaperlessBilling",
            "Churn"
        ],
        errors="ignore"
    )

    # Binary encoding
    X["gender"] = X["gender"].apply(
        lambda x: 1 if x == "Male" else 0
    )

    yes_no_cols = [
        "MultipleLines",
        "OnlineSecurity",
        "OnlineBackup",
        "DeviceProtection",
        "TechSupport",
        "StreamingTV",
        "StreamingMovies",
        "Partner",
        "Dependents",
        "PhoneService"
    ]

    for col in yes_no_cols:
        X[col] = X[col].apply(
            lambda x: 1 if x == "Yes" else 0
        )

    # Categorical encoding
    X["InternetService"] = X["InternetService"].apply(
        lambda x:
            2 if x == "Fiber optic"
            else 1 if x == "DSL"
            else 0
    )

    X["Contract"] = X["Contract"].apply(
        lambda x:
            1 if x == "Month-to-month"
            else 2 if x == "One year"
            else 3
    )

    return X

X_train, X_test, y_train, y_test = train_test_split(
    df.drop("Churn", axis=1),
    df["Churn"],
    test_size=0.2,
    random_state=42
)
#
# len(list(X_train.columns))
#
# models = {
#     "LogisticRegression": LogisticRegression(),
#
#     "DecisionTreeClassifier":
#         DecisionTreeClassifier(random_state=42),
#
#     "RandomForestClassifier":
#         RandomForestClassifier(random_state=42),
#
#     "KNeighboursClassifier":
#         KNeighborsClassifier(),
#
#     "SupportVectorClassifier":
#         SVC(probability=True, random_state=42),
#
#     "VotingClassifier":
#         VotingClassifier(
#             voting="hard",
#             estimators=[
#                 ("lr", LogisticRegression()),
#                 ("dt", DecisionTreeClassifier(random_state=42)),
#                 ("rf", RandomForestClassifier(random_state=42)),
#                 ("knn", KNeighborsClassifier()),
#                 ("svc", SVC(probability=True, random_state=42))
#             ]
#         )
# }
#
# counter = 0
#
# for model_name, model in models.items():
#
#     pipe = Pipeline([
#         ("custom cleaner", FunctionTransformer(data_preprocessor)),
#         ("model", model)
#     ])
#
#     # Train
#     pipe.fit(X_train, y_train)
#
#     # Predict ONCE
#     y_train_pred = pipe.predict(X_train)
#     y_test_pred = pipe.predict(X_test)
#
#     # Training metrics
#     train_precision = precision_score(
#         y_train,
#         y_train_pred,
#         pos_label="Yes"
#     )
#
#     train_recall = recall_score(
#         y_train,
#         y_train_pred,
#         pos_label="Yes"
#     )
#
#     train_accuracy = accuracy_score(
#         y_train,
#         y_train_pred
#     )
#
#     train_f1 = f1_score(
#         y_train,
#         y_train_pred,
#         pos_label="Yes"
#     )
#
#     # Test report
#     test_report = classification_report(
#         y_test,
#         y_test_pred
#     )
#
#     print(f"Result_{counter + 1}: {model_name}")
#     print("=" * 60)
#
#     print("TRAINING RESULTS")
#     print(f"Precision: {train_precision:.4f}")
#     print(f"Recall:    {train_recall:.4f}")
#     print(f"Accuracy:  {train_accuracy:.4f}")
#     print(f"F1 Score:  {train_f1:.4f}")
#
#     print("\nTEST RESULTS")
#     print(test_report)
#
#     # Confusion Matrix
#     ConfusionMatrixDisplay.from_predictions(
#         y_test,
#         y_test_pred,
#         display_labels=["No Churn", "Churn"]
#     )
#
#     plt.title(f"Confusion Matrix - {model_name}")
#     plt.show()
#
#     print("=" * 60)
#     print()
#
#     counter += 1

model = VotingClassifier(
            voting="hard",
            estimators=[
                ("lr", LogisticRegression()),
                ("dt", DecisionTreeClassifier(random_state=42)),
                ("rf", RandomForestClassifier(random_state=42)),
                ("knn", KNeighborsClassifier()),
                ("svc", SVC(probability=True, random_state=42))
            ])

choice_model = Pipeline([
        ("custom cleaner", FunctionTransformer(data_preprocessor)),
        ("model", model)
])

choice_model.fit(X_train, y_train)

model_dir = "../Telco_Churn_Project"
#os.makedirs(model_dir, exist_ok=True)

# Save
file_path = os.path.join(model_dir,"Telco_model.pkl")

with open(file_path, "wb") as f:
    pickle.dump(choice_model, f)

#df["Churn"].value_counts(normalize = True)

