# -*- coding: utf-8 -*-
"""Telco_Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0Nj7ftco70Bo1k_ywKt9LEnQHLZBqga
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import sklearn
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
from matplotlib import colormaps
sns.set_palette('Set3')
sns.set_style("darkgrid")
from warnings import filterwarnings
filterwarnings(action="ignore")
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder,OrdinalEncoder
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, confusion_matrix, precision_score, recall_score, accuracy_score, f1_score, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import FunctionTransformer
import pickle
import joblib
import os

print(f"numpy == {np.__version__}")
print(f"pandas == {pd.__version__}")
print(f"seaborn == {sns.__version__}")
print(matplotlib.__version__)
print(f"joblib == {joblib.__version__}")
print(f"scikit-learn {sklearn.__version__}")
file_path = "WA_Fn-UseC_-Telco-Customer-Churn.csv"
# Load the data into a pandas DataFrame
try:
    df = pd.read_csv(file_path)
    print(f"Data loaded successfully from {file_path}.")
except FileNotFoundError:
    print(f"Error: The file at {file_path} was not found. Please check the path and try again.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

"""**`Exploratory analysis`**"""

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors="coerce")

df.pivot_table(columns="Contract", aggfunc={"TotalCharges":"sum"})


def data_preprocessor(df):

    df = df.copy()

    # Convert TotalCharges to numeric
    df["TotalCharges"] = pd.to_numeric(
        df["TotalCharges"],
        errors="coerce"
    )

    df["TotalCharges"] = df["TotalCharges"].fillna(0)

    # Drop unnecessary columns
    X = df.drop(
        columns=[
            "customerID",
            "PaymentMethod",
            "PaperlessBilling",
            "Churn"
        ],
        errors="ignore"
    )

    # Binary encoding
    X["gender"] = X["gender"].apply(
        lambda x: 1 if x == "Male" else 0
    )

    yes_no_cols = [
        "MultipleLines",
        "OnlineSecurity",
        "OnlineBackup",
        "DeviceProtection",
        "TechSupport",
        "StreamingTV",
        "StreamingMovies",
        "Partner",
        "Dependents",
        "PhoneService"
    ]

    for col in yes_no_cols:
        X[col] = X[col].apply(
            lambda x: 1 if x == "Yes" else 0
        )

    # Categorical encoding
    X["InternetService"] = X["InternetService"].apply(
        lambda x:
            2 if x == "Fiber optic"
            else 1 if x == "DSL"
            else 0
    )

    X["Contract"] = X["Contract"].apply(
        lambda x:
            1 if x == "Month-to-month"
            else 2 if x == "One year"
            else 3
    )

    return X

X_train, X_test, y_train, y_test = train_test_split(
    df.drop("Churn", axis=1),
    df["Churn"],
    test_size=0.2,
    random_state=42
)


model = VotingClassifier(
            voting="hard",
            estimators=[
                ("lr", LogisticRegression()),
                ("dt", DecisionTreeClassifier(random_state=42)),
                ("rf", RandomForestClassifier(random_state=42)),
                ("knn", KNeighborsClassifier()),
                ("svc", SVC(probability=True, random_state=42))
            ])

choice_model = Pipeline([
        ("custom cleaner", FunctionTransformer(data_preprocessor)),
        ("model", model)
])

choice_model.fit(X_train, y_train)

model_dir = "../Telco_Churn_Project"
#os.makedirs(model_dir, exist_ok=True)

# Save
file_path = os.path.join(model_dir,"Telco_model.pkl")

with open(file_path, "wb") as f:
    pickle.dump(choice_model, f)


